# Copyright 2017 Damian Meden.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# See https://github.com/dmeden/tokenizer for library home page.


sudo: false

language: cpp

os: linux
    
branches:
  only:
    - develop
    - master
    - travis_support

matrix:
  exclude: 
    - language: cpp
    - os: linux
    - branches:
       only:
         - master
  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-4.7
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
install:
  - cd ..
  - git clone -b develop --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/static_assert
  - git submodule init libs/type_traits
  - git submodule init tools/build
  - git submodule update
  - ./bootstrap.sh
  - ./b2 headers
  - rcp -r $TRAVIS_BUILD_DIR libs/tokenizer/

script:
  - ./b2 libs/tokenizer/test toolset=$TOOLSET cxxflags=-std=c++11
  - ./b2 libs/tokenizer toolset=$TOOLSET
  