# Copyright 2017 Damian Meden.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# See https://github.com/dmeden/tokenizer for library home page.


sudo: false

language: cpp

os: linux
    
branches:
  only:
    - develop
    - master
    - travis_support

matrix:
  exclude: 
    - language: cpp
    - os: linux
    - branches:
       only:
         - master
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: TOOLSET=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: TOOLSET=clang

install:
  - cd ..
  - git clone -b develop --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init
  - ./bootstrap.sh
  - ./b2 headers
  - rcp -r $TRAVIS_BUILD_DIR libs/tokenizer/

script:
  - "echo 'using clang : 3.7 : clang++-3.7 ;' > $HOME/user-config.jam"
  - ./b2 libs/tokenizer/test toolset=$TOOLSET cxxflags=-std=c++11
  - ./b2 libs/tokenizer toolset=$TOOLSET cxxflags=-std=c++11
  